name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: bash .devcontainer/setup.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build counter
        run: bash counter_build.sh

      - name: Upload matching files
        uses: actions/upload-artifact@v4
        with:
          name: counter-artifacts
          path: |
            counter/schema/**
            counter/artifacts/**

      - name: Deploy counter
        run: bash counter_deploy.sh
